// <auto-generated />
namespace JJTrailerStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initseed0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initseed0));
        
        string IMigrationMetadata.Id
        {
            get { return "201502181326521_initseed--0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
