// <auto-generated />
namespace JJTrailerStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initseed1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initseed1));
        
        string IMigrationMetadata.Id
        {
            get { return "201502181515147_initseed-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
